### ISSUE TITLE
Any ETA for tensorcore/scope availability?

### ISSUE THREAD

**Issue by oscarbg** [c3sr/scope#46]
just quick read “Accelerating Reduction and Scan Using Tensor Core Units” and think code is part of scope tensorcore package, right? also do you plan on offering somewhere patches for your optimized cub as used in paper:
“CUB does not contain these shuffle-based optimizations for half precision. To make the evaluations fair and more technically meaningful, we implement these optimization for the half precision data type in CUB. The modified CUB is used for the evaluation to provide a more aggressive base of comparison”
thanks..

**Comment by abduld** [comment]
available at https://github.com/c3sr/tcu_scope
